### ISSUE TITLE
JFrog build info extractor 4.7.1

### ISSUE THREAD

**Issue by nhaarman** [wupdigital/android-maven-publish#16]
When using the `android-maven-publish:3.3.0` version with `build-info-extractor-gradle:4.7.1` a `NullPointerException` occurs (as in #15):

```
Caused by: java.lang.NullPointerException: Cannot get property 'allDependencies' on null object
        at digital.wup.android_maven_publish.AndroidVariantLibrary$RuntimeUsage.getRuntimeDependencies(AndroidVariantLibrary.groovy:125)
        at digital.wup.android_maven_publish.AndroidVariantLibrary$RuntimeUsage.getDependencies(AndroidVariantLibrary.groovy:114)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.from(DefaultMavenPublication.java:195)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:57)
        at publishing_f2u623pjjtsksb7vx5fy8t9vh$_run_closure2$_closure4$_closure5.doCall(/home/dev/myproject/ops/publishing.gradle:14)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.create(AbstractPolymorphicDomainObjectContainer.java:61)
        at org.gradle.api.internal.PolymorphicDomainObjectContainerConfigureDelegate._configure(PolymorphicDomainObjectContainerConfigureDelegate.java:44)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:66)
        at publishing_f2u623pjjtsksb7vx5fy8t9vh$_run_closure2$_closure4.doCall(/home/dev/myproject/ops/publishing.gradle:13)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:148)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:79)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:34)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.publish.internal.DefaultPublishingExtension.publications(DefaultPublishingExtension.java:48)
        at org.gradle.api.publish.internal.DefaultPublishingExtension_Decorated.publications(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:57)
        at publishing_f2u623pjjtsksb7vx5fy8t9vh$_run_closure2.doCall(/home/dev/myproject/ops/publishing.gradle:12)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.internal.ImmutableActionSet$CompositeSet.execute(ImmutableActionSet.java:196)
        at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configureNow(ExtensionsStorage.java:225)
        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.get(ExtensionsStorage.java:204)
        at org.gradle.api.internal.plugins.ExtensionsStorage.getAsMap(ExtensionsStorage.java:56)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.getProperties(DefaultConvention.java:286)
        at org.gradle.internal.metaobject.CompositeDynamicObject.getProperties(CompositeDynamicObject.java:79)
        at org.gradle.api.internal.project.DefaultProject$4.create(DefaultProject.java:1029)
        at org.gradle.api.internal.project.DefaultProject$4.create(DefaultProject.java:1027)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:240)
        at org.gradle.api.internal.project.DefaultProject.getProperties(DefaultProject.java:1027)
        at org.jfrog.gradle.plugin.artifactory.extractor.GradleArtifactoryClientConfigUpdater.fillProperties(GradleArtifactoryClientConfigUpdater.java:141)
        at org.jfrog.gradle.plugin.artifactory.extractor.GradleArtifactoryClientConfigUpdater.update(GradleArtifactoryClientConfigUpdater.java:61)
        at org.jfrog.gradle.plugin.artifactory.extractor.GradleArtifactoryClientConfigUpdater$update.call(Unknown Source)
        at org.jfrog.gradle.plugin.artifactory.extractor.listener.ProjectsEvaluatedBuildListener.evaluate(ProjectsEvaluatedBuildListener.groovy:56)
        at org.jfrog.gradle.plugin.artifactory.extractor.listener.ProjectsEvaluatedBuildListener$_afterEvaluate_closure1.doCall(ProjectsEvaluatedBuildListener.groovy:44)
        at org.jfrog.gradle.plugin.artifactory.extractor.listener.ProjectsEvaluatedBuildListener.afterEvaluate(ProjectsEvaluatedBuildListener.groovy:43)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:370)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:352)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
```

Downgrading `build-info-extractor-gradle` to `4.6.2` does not crash, but nothing gets published when running `artifactoryPublish`.

**Comment by warnyul** [comment]
Could you please try build-info-extractor plugin 4.7.3. I think [this](https://github.com/JFrogDev/build-info/issues/165) issue has been solved your issue. It was a problem in the build-info-extractor plugin and not the android-maven-publish plugin.

**Comment by nhaarman** [comment]
Yes, it seems that the following combination of versions works:

```
Gradle: 4.7
digital.wup:android-maven-publish:3.3.0
org.jfrog.buildinfo:build-info-extractor-gradle:4.7.3
```

**Comment by warnyul** [comment]
Sounds good. Thanks for the reply. I close this issue.
